builds:
  - main: ./main.go
    id: fastcommit
    binary: fastcommit
    skip: false
    env:
      - CGO_ENABLED=0
      - GOPROXY=https://goproxy.io
    targets:
      - "darwin_amd64"
      - "darwin_arm64"
#      - "windows_amd64"
      - "linux_amd64"
      - "linux_arm64"
    ldflags:
      - -X 'github.com/pubgo/funk/v2/buildinfo.version=v{{ .Version }}'
      - -X 'github.com/pubgo/funk/v2/buildinfo.project=fastcommit'
      - -X 'github.com/pubgo/funk/v2/buildinfo.buildTime={{ .CommitDate }}'
      - -X 'github.com/pubgo/funk/v2/buildinfo.commitID={{ .ShortCommit }}'
    flags:
      - -trimpath
      - -tags=releaser
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-{{ .Tag }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
report_sizes: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^chore'
    include:
      - '^feat'
      - '^fix'
      - '^perf'
      - '^refactor'
  use: git
  groups:
    - title: "New Features"
      regexp: "^feat"
    - title: "Bug Fixes"
      regexp: "^fix"
    - title: "Performance Improvements"
      regexp: "^perf"
    - title: "Refactors"
      regexp: "^refactor"

release:
  github:
    owner: pubgo
    name: fastcommit
  name_template: '{{ .ProjectName }} {{ .Tag }}'
  footer: |
    ## Installation
    Download the latest release from the [GitHub Releases](https://github.com/pubgo/fastcommit/releases) page.
