// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetGitHubAuthStatus(): $CancellablePromise<$models.GitHubAuthStatus> {
    return $Call.ByID(2218531742);
}

export function GetModules(): $CancellablePromise<$models.DesktopModule[] | null> {
    return $Call.ByID(1211788486);
}

export function GetRepoRoot(): $CancellablePromise<string> {
    return $Call.ByID(853311305);
}

export function RunAction(req: $models.ActionRunRequest): $CancellablePromise<$models.CommandResult> {
    return $Call.ByID(465937298, req);
}

export function SetGitHubToken(token: string): $CancellablePromise<void> {
    return $Call.ByID(35429655, token);
}

export function SetRepoRoot(path: string): $CancellablePromise<void> {
    return $Call.ByID(2463093517, path);
}
