// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ActionField {
    "key": string;
    "label": string;
    "placeholder": string;
    "required": boolean;
    "default": string;
}

export interface ActionRunRequest {
    "moduleID": string;
    "actionID": string;
    "values": { [_ in string]?: string } | null;
}

export interface CommandResult {
    "command": string;
    "output": string;
    "exitCode": number;
    "startedAt": string;
    "endedAt": string;
}

export interface DesktopModule {
    "id": string;
    "title": string;
    "description": string;
    "actions": ModuleAction[] | null;
}

export interface ModuleAction {
    "id": string;
    "title": string;
    "description": string;
    "tool": string;
    "args": string[] | null;
    "fields": ActionField[] | null;
}
