// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CommandResult {
    "command": string;
    "output": string;
    "exitCode": number;
    "startedAt": string;
    "endedAt": string;
}
